name: Ci test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup SBCL
      uses: cheeze2000/setup-sbcl@v1
      with:
        version: 2.3.2
    
    - name: Run Script
      run: sbcl --load main.lisp --eval "(main)"
